### ISSUE TITLE
Celery configuation 

### ISSUE THREAD

**Issue by LianYangCn** [wq/django-data-wizard#10]
README said:
```python
# myproject/settings.py

CELERY_RESULT_BACKEND = BROKER_URL = 'redis://localhost:6379/1'
```
and 
```python
# myproject/celery.py
app.config_from_object('django.conf:settings')
```

So, celery will read RESULT_BACKEND which not set, then you can **NOT** get the celery task result or status.

Is that why you update the importing status by django.model?

In my opinion, celery.result is elegant and more faster to implement the importing status

Wish you and your project better!

**Comment by sheppard** [comment]
Thanks for the feedback.  The Celery configuration was meant as an example and certainly could be improved.  The idea is to use the celery result backend for real-time updates but also log information in Django models (e.g. `RunLog` and `Record`) for later review.

Note that in the latest version of Django Data Wizard (1.1.0), celery is no longer the default backend.
