### ISSUE TITLE
Question: Are all the dependencies documented?

### ISSUE THREAD

**Issue by askpatrickw** [wq/django-data-wizard#16]
I followed along the basic setup and it when I tried to runserver I saw that Django rest framework was required.

And now when I try to run an import on a file I have no options when prompted to "Select a format (serializer) to continue."

Is it also required that I fully wire DRF to each model I want to use data-wizard with?

**Comment by sheppard** [comment]
You don't have to create a unique DRF serializer for each model, but you do need to explicitly register them with the wizard.  See https://github.com/wq/django-data-wizard#model-registration .  (This was documented before, but I added a heading to make it stand out more.)

I also added `djangorestframework` to the dependencies, thanks for the catch.

**Comment by askpatrickw** [comment]
And here I thought someone would you answer and I'd make a PR. Thanks for the full-service response!

**Comment by Wcollard** [comment]
I am getting bogged down with an import of an XML file that has nested relational tables  (one to one) or one to many relationships.  Is the Django Data Wizard set up for that? or it what we are trying to do too complicated
