### ISSUE TITLE
Element a tag is not closed

### ISSUE THREAD

**Issue by JakLiao** [wq/django-data-wizard#17]
https://github.com/wq/django-data-wizard/blob/eda8f67ad6a24caf0cabe16d933cb5ea6d14888f/data_wizard/templates/data_wizard/run_list.html#L29

This "td" should change to "a".

**Comment by sheppard** [comment]
Thanks, I will make sure this is fixed in the next release.

**Comment by sheppard** [comment]
Fixed in #21.
