### ISSUE TITLE
Import Number without float point

### ISSUE THREAD

**Issue by bomba1990** [wq/django-data-wizard#20]
Than you very much for this library. I am using it to import zip code from an XLS file to a model on Django. 

But I have one small issue that it takes the Zipcode like a number and it's imported with the floating-point at the end of the string. For example, the Zipcode says "12345" it imports like "12345.0"

I checked the code but not find any solution to this issue.

**Comment by sheppard** [comment]
Yest, this is due in part the XLS cell being formatted as a number.  One easy way to fix this is to register a [custom serializer class](https://github.com/wq/django-data-wizard#custom-serializers) with a field that converts the number to `int` and then to `string`.  So, instead of:

```python
# myapp/wizard.py
import data_wizard
from .models import Address

data_wizard.register(Address)
```

You could do this:

```python
# myapp/wizard.py
from rest_framework import serializers
import data_wizard
from .models import Address

class NumericCharField(serializers.CharField):
    def to_internal_value(self, data):
        if isinstance(data, float):
            data = int(data)
        return str(data)

class AddressSerializer(serializers.ModelSerializer):
    postal_code = NumericCharField()
    class Meta:
        model = Address
        fields = "__all__"

data_wizard.register('Address with Zip Code', AddressSerializer)
```

**Comment by bomba1990** [comment]
Thank you very much work really well.
