### ISSUE TITLE
ImportError with DRF >= 3.8

### ISSUE THREAD

**Issue by funkindy** [wq/django-data-wizard#22]
`detail_route` decorator was merged into `action` since DRF 3.8, so the line ` from rest_framework.decorators import detail_route` causes ImportError and the app wont start:

`ImportError: cannot import name 'detail_route' from 'rest_framework.decorators'`

Docs:
https://www.django-rest-framework.org/community/3.8-announcement/#action-decorator-replaces-list_route-and-detail_route

**Comment by sheppard** [comment]
Thanks, this will be fixed in the next release.

**Comment by sheppard** [comment]
[Data Wizard 1.2.0](https://github.com/wq/django-data-wizard/releases/tag/v1.2.0) is now available on PyPI.
