### ISSUE TITLE
DataError: integer out of range with Postgres

### ISSUE THREAD

**Issue by chirdeeptomar** [wq/django-data-wizard#30]
I am getting an error importing data with both excel and csv.  I see only one record being entered into the table. I have IDs as uuid and not as int. My assumption is the library is somewhere storing the id of the entered record and storing it as in Int. 

```
ERROR:root:integer out of range
Traceback (most recent call last):
  File "/home/chirdeep/env/swadeshi-khoj/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: integer out of range
```

I have also tried with SQLite, same issue. Thanks for your help .

**Comment by sheppard** [comment]
Yes, the default row logging functionality assumes that the primary key is an integer.  I added a [new configuration option](https://django-data-wizard.wq.io/config/settings) to make it possible to override or disable this functionality, which is not critical for getting data into the database.
