### ISSUE TITLE
ImportError: cannot import name 'MutableMapping' from 'collections' 

### ISSUE THREAD

**Issue by codepypl** [wq/django-data-wizard#37]
hey guys, I  use django 4.0.3
after i installed the package from pip , when i tried to run it i crashed
i manage to fix it by editing:
admin.py
from 
from django.utils.translation import ugettext_lazy as _
to:
from django.utils.translation import gettext as _

and signals.py

from :
from django.dispatch import Signal
import_complete = Signal(providing_args=['run', 'status'])
new_metadata = Signal(providing_args=['run', 'identifier'])
progress = Signal(providing_args=['run', 'status', 'meta'])

to:
from django.dispatch import Signal
import_complete = Signal()
new_metadata = Signal()
progress = Signal()

the problem i have is :

ImportError: cannot import name 'MutableMapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by sheppard** [comment]
This is fixed in the latest release.
