### ISSUE TITLE
django template based interface

### ISSUE THREAD

**Issue by sheppard** [wq/django-data-wizard#7]
Currently the interface uses Mustache templates designed to be used with applications built with the [wq framework](https://wq.io).  For non-wq users, it would be nice to also provide a default interface based on Django templates, perhaps integrated with the Django admin and/or DRF's built-in API browser.

**Comment by amitsquare** [comment]
any improvement here ?
Or documentation for this .

**Comment by sheppard** [comment]
This is now available in version [1.1.0](https://github.com/wq/django-data-wizard/releases/tag/v1.1.0).
