### ISSUE TITLE
KeyError at /datawizard/  'content_object'. Full example of simplest configuration.

### ISSUE THREAD

**Issue by om2c0de** [wq/django-data-wizard#8]
Hi Andrew! "django-data-wizard" is a great thing and I want to add it to my project for mapping data from recent uploaded spreadsheets but I was trying to send initial POST request to create object with its own id but I've got a strange error and I don't understand how to solve it..Can you please help me with solving this issues and if its really works well like on screenshots, I'll donate few bucks for your project. Thanks, Alexandr. P.S I've add screenshot of all my files, that I've used for initial config on one screenshot of my emacs. So I think that I've done all like in README of your repo, then create view which sends POST request, and this should create object of my model, so I don't understand this moment, I just want to see and configure headers of my excel or csv file, and save them correct in database..
<img width="1280" alt="screen shot 2018-01-07 at 11 21 27" src="https://user-images.githubusercontent.com/24379113/34647888-1d6862b8-f3a0-11e7-9c88-c79fdeb0d9be.png">

<img width="1280" alt="screen shot 2018-01-07 at 11 22 02" src="https://user-images.githubusercontent.com/24379113/34647881-e5bceadc-f39f-11e7-8db3-cc5f6249c0c5.png">

**Comment by sheppard** [comment]
I simplified the configuration so you can now use the Django admin to upload files and initialize new wizard runs.  See the new [installation docs](https://github.com/wq/django-data-wizard#installation) for more information.

**Comment by om2c0de** [comment]
Sounds great, thanks !!
